server.port=8080
spring.application.name=OnlineStore
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/OnlineStore?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oluwadamilola@77
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.h2.console.enabled=true

spring.app.jwtSecret=dondamzySecretKey7#
spring.app.jwtExpirationMs=3000000000

